### ISSUE TITLE
/usr/bin/ld: can't find -lncnn

### ISSUE THREAD

**Issue by ZhengQiushi** [XinghaoChen9/LiveFaceReco_RaspberryPi#2]
I try to build your project on my Laptop using CLion . Unluckily , I met the error "/usr/bin/ld: can't find -lncnn" in the building process.I wonder if you install some other source lib before or not . I would be appreciated if you can help me !

**Comment by XinghaoChen9** [comment]
I have updated lib files in the "include" folder. If other system is used, please change the path of ncnn lib file to the correct one.
```
#select the corresponding lib file
#LINK_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/include/libs/ubuntu)
#LINK_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/include/libs/arm64-v8a)
#LINK_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/include/libs/armeabi-v7a)
LINK_DIRECTORIES(${CMAKE_CURRENT_LIST_DIR}/include/libs/RaspberryPi4B)
```
