### ISSUE TITLE
make  最后一步 报错

### ISSUE THREAD

**Issue by konglingzheng** [XinghaoChen9/LiveFaceReco_RaspberryPi#3]
我在 树莓派 和nano 遇到了一样的问题；
树莓派系统：ubuntu mate 20.0
nano 系统：18.04
同样报错：“当搜索用于 /home/zyolo/下载/人脸打卡/LiveFaceReco_RaspberryPi-master/include/libs/ubuntu/libncnn.a 时跳过不兼容的 -lncnn
/usr/bin/ld: 找不到 -lncnn”
都显示-lncnn不兼容，  ubunutu，arm64-v8a，armeabi-v7a和RaspberryPi4B 四个包都试了
还请大佬赐教！！！！！！！！！！！！！！！！！！！！！！万分感谢

**Comment by XinghaoChen9** [comment]
用nano的话建议重新克隆ncnn并且编译libncnn.a文件，再替代RaspberryPi4B目录下面文件，大概率是因为不兼容造成的，欢迎更新后续情况。

**Comment by konglingzheng** [comment]
可以加微信吗大佬

**Comment by XinghaoChen9** [comment]
建议在issue区讨论哈，这样大家有相同的问题都可以看到。

**Comment by konglingzheng** [comment]
make 报的新错误
LiveFaceReco_RaspberryPi-master/include/libs/arm64-v8a/libncnn.a(cpu.cpp.o)：在函数‘ncnn::set_cpu_powersave(int)’中：
/home/yuanhao/osc/ncnn-20200413/src/cpu.cpp:376：对‘__sF’未定义的引用

LiveFaceReco_RaspberryPi-master/include/libs/arm64-v8a/libncnn.a(net.cpp.o)：在函数‘ncnn::Net::load_param_bin(AAssetManager*, char const*)’中：
/home/yuanhao/osc/ncnn-20200413/src/net.cpp:671：对‘AAssetManager_open’未定义的引用

好多这种错误

**Comment by XinghaoChen9** [comment]
克隆ncnn `git clone --recursive https://github.com/Tencent/ncnn.git`
编译ncnn库可以参考  `https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-raspberry-pi-3`

**Comment by konglingzheng** [comment]
ncnn库编译完了  接下来如何编译libncnn.a文件 来替代RaspberryPi4B目录下面文件

**Comment by XinghaoChen9** [comment]
按照步骤来的话，应该会在build目录下，可以搜索一下。然后直接替换就好，记得cmakelist里面修改为对应的文件夹。

**Comment by konglingzheng** [comment]
谢谢大佬  nano  已经成功编译运行
感谢感谢！！！！！！！！！！！！！！！！！！！！！！！！！！1

**Comment by XinghaoChen9** [comment]
恭喜，还有什么问题欢迎issue。之后有时间可以把你编译好的libncnn.a文件发个链接给我，我也更新一下。

**Comment by konglingzheng** [comment]
https://github.com/konglingzheng/nano_ncnn_libncnn.a
nano 4.3 ubuntu18.04

**Comment by XinghaoChen9** [comment]
感谢，已经更新。这会帮助到其他nano用户。
