### ISSUE TITLE
面部识别距离有点近

### ISSUE THREAD

**Issue by konglingzheng** [XinghaoChen9/LiveFaceReco_RaspberryPi#4]
好像稍微远一点的面部就检测不到  const int distance_threshold = 10;
const float face_thre=0.1;
效果也不太明显

请问大神有什么高招吗！感谢！！

**Comment by XinghaoChen9** [comment]
` face_thre`是识别的阈值，distance_threshold=10是高度差最低为10个像素的人脸就可以检测，不行的话请检查环境光照，清晰度之类的因素。

**Comment by konglingzheng** [comment]
和照片缩放的大小有关系吗

**Comment by XinghaoChen9** [comment]
只要是通过`record_face`正常拍摄的就没问题。
