### ISSUE TITLE
人脸识别的相似度

### ISSUE THREAD

**Issue by tanggt** [XinghaoChen9/LiveFaceReco_RaspberryPi#5]
您好，实际测试发现人脸识别的相似度最高也没有0.9，最好的都在0.8左右，而且以前的图像作为样本和现在对比的相似度也很低，想问下这个是不是正常的，还有没有办法提高相似度，我看小区的人脸识别相似度都在95%左右的相似度，感谢

**Comment by XinghaoChen9** [comment]
0.4是cos距离，一般大于0.4可以认为是同一个人。你说的是置信度，Arcface完全可以映射0.4到95%的置信度，详见[insightface](https://github.com/deepinsight/insightface)项目

**Comment by tanggt** [comment]
感谢 不过刚刚看了insight的特征维度是512，但是我们选用了128 ，不过置信度我这边最高只能到0.81

**Comment by XinghaoChen9** [comment]
是的，因为采用的是MobileFaceNet模型。0.81只是余弦距离，置信度你可以自己按需映射，这个影响并不大。

**Comment by tanggt** [comment]
好的  非常感谢！ 最近刚好学习这一块人脸识别，一直在学习您的代码。另外还发现一个问题，mtcnn检测人脸的时候有误报，ONet输出的人脸目标框有误报，比如实际就一个人脸，但是检测到3个人脸位置，3个误报，一直没发现原因。

**Comment by XinghaoChen9** [comment]
这个问题我没有遇到过，是在图片上标注出来了吗？后续有时间我再更新下retinaface的内容，效果应该会好一些。

**Comment by tanggt** [comment]
嗯嗯 好的  感谢  误报确实存在 我在图像画出来了 我最近再认真看看  thanks！
